name: adf_artifacts
 
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "adf_publish" ]
 
  # Allows you to run this workflow manually from the Actions tab
 
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 


      - name: Login via Az module
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 

      - name: Deploy resources
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: 'cicdadf'
          dataFactoryName: 'Va-adf-dev-devops'
          armTemplateFile: 'Va-adf-dev-devops/ARMTemplateForFactory.json'
          armTemplateParametersFile: 'Va-adf-dev-devops/ARMTemplateParametersForFactory.json'
      # additionalParameters: 'key1=value key2=value keyN=value' [optional]
      # skipAzModuleInstallation: true [optional]
      
